/**
 * Context Compression Types
 *
 * Defines types for the three-tier compression architecture:
 * - L1: Format compression (lossless, <1ms)
 * - L2: Extractive compression (TextRank, ~10ms)
 * - L3: Abstractive compression (LLM, ~1s)
 */

/**
 * Compression level
 */
export type CompressionLevel = 'L1' | 'L2' | 'L3' | 'L1+L2' | 'L1+L2+L3';

/**
 * Result of compression operation
 */
export interface CompressionResult {
  /** Compressed text */
  compressed: string;
  /** Original token count */
  originalTokens: number;
  /** Compressed token count */
  compressedTokens: number;
  /** Compression ratio (0-1, higher = more compression) */
  ratio: number;
  /** Estimated information retention (0-1) */
  infoRetention: number;
  /** Compression method used */
  method: string;
  /** Time taken in ms */
  latencyMs: number;
}

/**
 * Compression plan generated by the orchestrator
 */
export interface CompressionPlan {
  /** Compression level to use */
  level: CompressionLevel;
  /** Estimated compression ratio */
  estimatedRatio: number;
  /** Estimated latency */
  estimatedLatency: string;
  /** Reason for choosing this level */
  reason: string;
}

/**
 * Compressor interface
 */
export interface Compressor {
  /** Compressor name */
  readonly name: string;
  /** Compress text, optionally targeting a specific token count */
  compress(text: string, targetTokens?: number): Promise<CompressionResult> | CompressionResult;
}

/**
 * LLM client interface for L3 compression
 */
export interface CompressionLLMClient {
  /**
   * Generate completion from LLM
   */
  complete(prompt: string, maxTokens: number): Promise<string>;
}

/**
 * Age zone for progressive compaction
 */
export interface AgeZone {
  /** Zone name */
  name: string;
  /** Maximum age in turns */
  maxAge: number;
  /** Compression level for this zone */
  compressionLevel: 'none' | 'L1' | 'L1+L2' | 'L1+L2+L3';
}

/**
 * Message with turn number for progressive compaction
 */
export interface TimedMessage {
  /** Turn number */
  turn: number;
  /** Message role */
  role: string;
  /** Message content */
  content: string;
}

/**
 * Default age zones for progressive compaction
 */
export const DEFAULT_AGE_ZONES: AgeZone[] = [
  { name: 'hot', maxAge: 5, compressionLevel: 'none' },
  { name: 'warm', maxAge: 20, compressionLevel: 'L1' },
  { name: 'cool', maxAge: 50, compressionLevel: 'L1+L2' },
  { name: 'cold', maxAge: Infinity, compressionLevel: 'L1+L2+L3' },
];

/**
 * Compression statistics
 */
export interface CompressionStats {
  /** Total compressions performed */
  totalCompressions: number;
  /** Average compression ratio */
  avgRatio: number;
  /** Average latency in ms */
  avgLatencyMs: number;
  /** Total tokens saved */
  totalTokensSaved: number;
  /** Breakdown by level */
  byLevel: Record<CompressionLevel, {
    count: number;
    avgRatio: number;
    avgLatencyMs: number;
  }>;
}
