/**
 * bee — Compression types.
 *
 * Types for the three-tier compression architecture:
 * - L1: Format compression (lossless, <1ms)
 * - L2: Extractive compression (TextRank, ~10ms)
 * - L3: Abstractive compression (LLM, ~1s)
 */

/**
 * Compression level
 */
export type CompressionLevel = 'L1' | 'L2' | 'L3' | 'L1+L2' | 'L1+L2+L3';

/**
 * Result of a compression operation
 */
export interface CompressionResult {
  compressed: string;
  originalTokens: number;
  compressedTokens: number;
  /** Compression ratio (0-1, higher = more compression) */
  ratio: number;
  /** Estimated information retention (0-1) */
  infoRetention: number;
  method: string;
  latencyMs: number;
}

/**
 * Compression plan generated by the orchestrator
 */
export interface CompressionPlan {
  level: CompressionLevel;
  estimatedRatio: number;
  estimatedLatency: string;
  reason: string;
}

/**
 * Compressor interface
 */
export interface Compressor {
  readonly name: string;
  compress(text: string, targetTokens?: number): Promise<CompressionResult> | CompressionResult;
}

/**
 * LLM client interface for L3 compression
 */
export interface CompressionLLMClient {
  complete(prompt: string, maxTokens: number): Promise<string>;
}

/**
 * Age zone for progressive compaction
 */
export interface AgeZone {
  name: string;
  maxAge: number;
  compressionLevel: 'none' | 'L1' | 'L1+L2' | 'L1+L2+L3';
}

/**
 * Default age zones for progressive compaction
 */
export const DEFAULT_AGE_ZONES: AgeZone[] = [
  { name: 'hot', maxAge: 5, compressionLevel: 'none' },
  { name: 'warm', maxAge: 20, compressionLevel: 'L1' },
  { name: 'cool', maxAge: 50, compressionLevel: 'L1+L2' },
  { name: 'cold', maxAge: Infinity, compressionLevel: 'L1+L2+L3' },
];

/**
 * Compression statistics
 */
export interface CompressionStats {
  totalCompressions: number;
  avgRatio: number;
  avgLatencyMs: number;
  totalTokensSaved: number;
  byLevel: Record<CompressionLevel, {
    count: number;
    avgRatio: number;
    avgLatencyMs: number;
  }>;
}

/**
 * Create empty compression stats
 */
export function createEmptyStats(): CompressionStats {
  return {
    totalCompressions: 0,
    avgRatio: 0,
    avgLatencyMs: 0,
    totalTokensSaved: 0,
    byLevel: {
      L1: { count: 0, avgRatio: 0, avgLatencyMs: 0 },
      L2: { count: 0, avgRatio: 0, avgLatencyMs: 0 },
      L3: { count: 0, avgRatio: 0, avgLatencyMs: 0 },
      'L1+L2': { count: 0, avgRatio: 0, avgLatencyMs: 0 },
      'L1+L2+L3': { count: 0, avgRatio: 0, avgLatencyMs: 0 },
    },
  };
}
